import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { fetchVerticalChartData} from './verticalChartAPI';

export interface VerticalChartState {
  data: [{ code: number, name: string }]
  status: 'idle' | 'loading' | 'failed';
}

const initialState: VerticalChartState = {
  data:  [{ code: 0 , name: ''}],
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchAsync = createAsyncThunk(
    'lineChart/fetchData',
    async () => {
      const response = await fetchVerticalChartData();
      return response.data;
    }
);

export const verticalChartSlice = createSlice({
  name: 'lineChart',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setData: (state, action: PayloadAction<[{ code: number, name: string }]>) => {
      state.data = action.payload;
    },
    clearData: (state) => {
      state.data = [{ code: 0 , name: '' }];
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
        .addCase(fetchAsync.pending, (state) => {
          state.status = 'loading';
        })
        .addCase(fetchAsync.fulfilled, (state, action) => {
          state.status = 'idle';
          state.data = action.payload;
        });
  },
});

export const { setData, clearData } = verticalChartSlice.actions;
export const selectVerticalChartData = (state: RootState) => state.verticalChartData.data;
export default verticalChartSlice.reducer;